#!/bin/sh
#PBS -N tests
#PBS -joe
#PBS -l nodes=1:ppn=2
#PBS -lmem=1gb
#-----------------------------------------------------------
# For arina with the new "torque" queuing system
#
echo Running on `hostname`
echo This jobs runs on the following processors:
echo `cat $PBS_NODEFILE`
NPROCS=`wc -l < $PBS_NODEFILE`
echo This job has allocated $NPROCS nodes
#

cd $PBS_O_WORKDIR

prog=../../../Src/siesta

make SIESTA="mpirun $prog"


## Maybe:    
## make SIESTA="mpirun --gm-kill 600 $prog"



